### ISSUE TITLE
Enable conjugation

### ISSUE THREAD

**Issue by moble** [moble/quaternion#1]
_From @moble on October 16, 2014 2:6_

If I have a `np.quaternion` object `q`, then `q.conjugate()` and `q.conj()` do nothing.  In fact, I can't get the conjugate function to work in any case at all...

_Copied from original issue: moble/numpy_quaternion#1_

**Comment by jonlong-symbio** [comment]
I've sent an upstream patch for this issue as https://github.com/numpy/numpy/pull/9003.

**Comment by longjon** [comment]
I've sent an upstream patch for this issue as https://github.com/numpy/numpy/pull/9003.

**Comment by moble** [comment]
Thank you!  I can verify that your patch does indeed fix this problem.  I'll mention that on the numpy PR.

My statements above were not really clear enough.  In particular, it wasn't clear that the problem applies to *arrays* of quaternions rather than individual quaternions.  So I'll just write a simple test that shows the problem

```python
import numpy as np
import quaternion

q = np.array([np.quaternion(1,2,3,4), np.quaternion(5,6,7,8)])
q_c = np.array([np.quaternion(1,-2,-3,-4), np.quaternion(5,-6,-7,-8)])

assert np.array_equal(q.conjugate(), q_c)
```

**Comment by longjon** [comment]
With the merge of https://github.com/numpy/numpy/pull/9061, this is fixed upstream (and as of numpy 1.13).

**Comment by moble** [comment]
Thanks for all that work!  I'll keep an eye out for the 1.13 release and rebuild the conda packages.  Meanwhile, I'll leave this open as a reminder to myself to do that.

**Comment by moble** [comment]
Actually, I just realized that the 1.13 release hasn't come out on conda yet, so I'll leave this open still.
