### ISSUE TITLE
imag does not work on numpy arrays

### ISSUE THREAD

**Issue by 2sn** [moble/quaternion#103]
**Describe the bug**

The `.imag` property does not work in numpy arrays of quaternions.
(you added it for scalars)

**To Reproduce**

What does work is
```python
import numpy as np
import quaternion as quat

q = quat.quaternion(1,2,3,4)
q.imag
# returns: array([2., 3., 4.])

x = np.array(quat.quaternion(1,2,3,4))
x[()].imag
# returns: array([2., 3., 4.])
```
What fails is use in np.ndarray

```python
import numpy as np
import quaternion as quat

x = np.array(quat.quaternion(1,2,3,4))
x.imag
# returns: array(quaternion(0, 0, 0, 0), dtype=quaternion)
# expected: array([[2,3,4]])

np.imag(x)                         
# returns: array(quaternion(0, 0, 0, 0), dtype=quaternion)
# expected: array([[2,3,4]])

x = np.array([quat.quaternion(1,2,3,4), quat.quaternion(5,6,7,8)])
x.imag
# returns: array([quaternion(0, 0, 0, 0), quaternion(0, 0, 0, 0)], dtype=quaternion)
# expected: array([[2,3,4],[6,7,8]])

```

**Expected behavior**
It would be really great if the numpy `.imag` could also rerun the correct imaginary parts, since it also does not have a `.vec` attribute that you state you like to use for the scalar version.  (At the very least, until fixed, make it raise an error rather than returning a wrong result; I hope the modification is modest, but would go a long way!)

**Environment (please complete the following information):**
 - OS, including version: Fedora 29
 - Installation method: pip, python 3.7.2 installed from source
 - Numpy version (use `np.version.version`) 1.16.1
 - Quaternion version (use `quaternion.__version__`)  2019.2.16.13.38.20

**Additional context**
I would like to use that spot to thank you for the otherwise very nice package.

**Comment by moble** [comment]
Unfortunately, this is something that numpy doesn't currently support, though it is something I've looked into, and I try to keep an eye on numpy's support.  As suggested [here](https://github.com/moble/quaternion/issues/87#issuecomment-411720447), I expect the fastest way to get the part you want is with something like this:
```python
quaternion.as_float_array(q)[:, 1:]
```
