### ISSUE TITLE
RuntimeError: The NumPy package already has a quaternion type when using in IPython console (e.g. Spyder)

### ISSUE THREAD

**Issue by kevinkit** [moble/quaternion#106]
Executing a script twice in the same IPython console will result in the error:

`RuntimeError: The NumPy package already has a quaternion type when using in IPython console (e.g. Spyder)`. This can simply be done by the following script:

```python
import numpy as np
import quaternion

print(quaternion.z * quaternion.x)
```

**Expected behavior**
Any other package works with an import, the behaviour origins from the line:

```
if 'quaternion' in np.__dict__:
    raise RuntimeError('The NumPy package already has a quaternion type')
```

in init.py. 

**Environment (please complete the following information):**
 - Windows 10
 - pip install 
 - 1.15.4
 - 2019.2.21.14.1.1

**Additional context**
Using a new console is my current workaround

**Comment by moble** [comment]
I can't reproduce this error, even using spyder (which I don't normally do).  It's not clear how you're actually running this script, but you must be doing something that is not recommended for python.  In particular, whenever python sees an `import` statement, it first checks whether or not the package has already been imported; if so, it just skips the import step.  Your error message indicates that `quaternion` _has_ already been imported (which is how `numpy` knows about quaternions), and is being imported again.  So you must be doing something else to fool python into thinking it hasn't imported `quaternion` — like deleting `quaternion` in the mean time, or modifying the global dictionary.  Or maybe your installation of python itself is screwed up.  In any case, this is not an issue I can address; it's something peculiar about your setup.

If you can't figure out what's causing this problem, you could just work around it by using this:
```python
try:
    import quaternion
except RuntimeError:
    pass
```
It's a really bad idea, of course...
