### ISSUE TITLE
update constructor such that it better conforms to numpy API

### ISSUE THREAD

**Issue by 2sn** [moble/quaternion#108]
**Problems.**
1) `np.mean` does not work as it tries to do `ret.dtype.type(ret / rcount)` (`/site-packages/numpy/core/_methods.py(85)_mean()`) where `ret` is the quaternion.

2) Similar, one can create complex numbers with just the real (scalar) part by `np.compex(3)`.  Something similar does not work for the current quaternions implementation.

One initialise complex numbers from existing complex numbers, such as (np.complex(1+2j)).  The same does not work for the current quaternions implementation: 
```python
q = quaternion.quaternion(1,2,3,4)
q = quaternion.quaternion(q)
```
This is another manifestation of Issue (1).

**The solution I'd prefer.**
1) create scalar quaternions form scalars
```python
q = quaternion.quaternion(1.)
```

2) create quaternions from quaternions
```python
q = quaternion.quaternion(1,2,3,4)
q = quaternion.quaternion(q)
```
And similar for np arrays.

**Comment by moble** [comment]
Good suggestions.  I've implemented them now in master.

By the way, I'm not sure if you're using `np.mean` just as an example, or if you're actually using it for some purpose, but the only application that I know of for taking "means" of quaternions is actually already implemented (though it was not easily found before).  You can find it in `quaternion.mean_rotor_in_chordal_metric`.  The `np.mean` will likely return a non-unit quaternion, which is not helpful for rotations — which is what most people use quaternions for.  A bit surprisingly, just normalizing the sum actually *does* give a meaningful result.

**Comment by 2sn** [comment]
Dear Mike,

yes, your library is focused on nit quaternions for rotations, I assume 
the most common application.  I would have preferred a separated-out 
library that just deals with general quaternions with the highest 
possible integration with numpy, and then use that as backend for a 
rotation library - kind of what I do for my application, using the 
quaternion portion only. (as found on Wikipedia, using quaternions to 
compose rotations is most efficient, but then applying to large set of 
vectors, using the matrix multiplication is faster)

I was using the mean for testing when using different routines doing 
conversions of rotations; when going in a circle whether I get out what 
I put in.

Thanks for the update and all your work on that!

Best wishes,
Alexander
