### ISSUE TITLE
RuntimeError: Input contains unnormalized quaternions

### ISSUE THREAD

**Issue by mabouseif** [moble/quaternion#111]
Hello everyone : )

I have been struggling for a while with this, but i have two sets of data, and one works fine, and the other throws:
RuntimeError: Input contains unnormalized quaternions at indices...

although they are normalized. Can anyone help me with this?

Thanks : )

**Comment by moble** [comment]
This package does not emit any such error.  My best guess is that you're looking at the wrong `quaternion` package.  I suggest that you find the right one and ask a *specific* question — including a minimal code example that allows your issue to be reproduced.  Telling people that you get an error is not enough information for them to be able to help you.
