### ISSUE TITLE
power of 2 fails for array of quaternions

### ISSUE THREAD

**Issue by abarnert-pg** [moble/quaternion#123]
**Describe the bug**
Attempting to raise any array of quaternions to a power (whether you do it with `a ** n`, `pow(a, n)`, or `np.power(a, n)`) fails if the power happens to be equal to 2.0, with `TypeError: ufunc 'square' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`.

**To Reproduce**
```python
import numpy as np
import quaternion

q = np.quaternion(1,2,3,4)
a = np.array([q])
a ** 2
```

**Expected behavior**
```
array([quaternion(-28, 4.00000000000001, 6.00000000000001, 8.00000000000001)]
```
… which is the same as `np.array([q**2])`. Or maybe:
```
array([quaternion(-28, 4, 6, 8)], dtype=quaternion)
```
… which is the same as `a * a`.

**Environment (please complete the following information):**

 - OS, including version: macOS Mojave 10.14.6
 - Installation method (conda, pip, or compiled from source): pip
 - Numpy version (use `np.version.version`): 1.16.4
 - Quaternion version (use `quaternion.__version__`): 2019.7.23.15.26.49

**Additional context**
The problem appears to be that numpy is too clever, and its `power` algorithm special-cases 2.0 by calling the (presumably more efficient) `square` algorithm, but your quaternions don't support that method.

If so, the solution seems obvious: implement `square`. Even though nobody's likely to call it directly, if numpy wants to call it indirectly…

**Comment by abarnert-pg** [comment]
By the way, there is a workaround: instead of `a ** n`, you can use `a ** (n+0j)`. But I don't think anyone would _expect_ this to work (especially since `q ** (n+0j)` raises a `TypeError`) unless they thought about how this is probably implemented. And, even if you do discover it, it's hardly a model of readability.

**Comment by moble** [comment]
Thanks for opening this.  I agree with your diagnosis.  In the past I've been unable to fix problems like this without just overwriting numpy's own ufuncs (which I don't want to do for obvious reasons).  But more recently, they've improved the ways that ufuncs function, so I might be able to tie into that.  I'll look into it.

**Comment by moble** [comment]
Your example code works now.  Thanks again.
