### ISSUE TITLE
Inconsistent results from `as_euler_angles`

### ISSUE THREAD

**Issue by sierracodes** [moble/quaternion#127]
**Note about Euler angles**
I have read the guidelines regarding Euler angles, and accept that the Euler angle conventions selected by the package are arbitrary, but not "wrong" in any sense. This bug illustrates a failure to match the stated conventions at: https://github.com/moble/quaternion/wiki/Euler-angles-are-horrible#conventions.

**Describe the bug**
The result of `as_euler_angles` no longer produces a set of Euler angles which match the definition described at: https://github.com/moble/quaternion/wiki/Euler-angles-are-horrible#conventions

In particular, when starting with a normalized quaternion `q`, `from_euler_angles(as_euler_angles(q))` no longer produces a quaternion equal to `q`.

**To Reproduce**

```python
import quaternion

q0 = quaternion.quaternion(0, 0.6, 0.8, 0)
assert q0.norm() == 1.0

euler_angles = quaternion.as_euler_angles(q0)
# In 2019.9.30.17.47.33, this yields: [0.         3.14159265 0.        ]
# In 2019.7.23.15.26.49, this yields: [-0.64350111  3.14159265  0.64350111]
print(euler_angles)

q0_derived = quaternion.from_euler_angles(euler_angles)
# In 2019.9.30.17.47.33: quaternion(6.12323399573677e-17, -0, 1, 0)
# In 2019.7.23.15.26.49: quaternion(6.12323399573677e-17, 0.6, 0.8, 0)
print(q0_derived)

# Manual calculation from definition given at
# https://github.com/moble/quaternion/wiki/Euler-angles-are-horrible#conventions
alpha, beta, gamma = euler_angles
Q = (
    (alpha * quaternion.z / 2).exp()
    * (beta * quaternion.y / 2).exp()
    * (gamma * quaternion.z / 2).exp()
)
# In 2019.9.30.17.47.33: quaternion(6.12323399573677e-17, 0, 1, 0)
# In 2019.7.23.15.26.49: quaternion(6.12323399573677e-17, 0.6, 0.8, 0)
print(Q)
```
The issue can also be illustrated with `quaternion(0, 1, 0, 0)`, `quaternion(0.6, 0, 0, 0.8)`, and many other normalized quaternions.

**Expected behavior**
I expect `from_euler_angles(as_euler_angles(q))` to return a quaternion equivalent to `q` (assuming `q` is normalized), and I expect the resulting Euler angles to match the [stated conventions](https://github.com/moble/quaternion/wiki/Euler-angles-are-horrible#conventions). Namely, I expect the behavior from version `2019.7.23.15.26.49`.

**Environment (please complete the following information):**
 - Ubuntu 18.04 (in Docker container)
 - Installed via `pip`
 - Numpy version: 1.16.4
 - Quaternion version: 2019.9.30.17.47.33

**Additional context**

I believe the bug was introduced by this commit: https://github.com/moble/quaternion/commit/ae89333786842cdd3d0058c03ab81a19ca56df4b. 

The issue exists in version `2019.9.30.17.47.33`, but not version `2019.7.23.15.26.49`.

**Comment by moble** [comment]
Thanks for the very thorough report.  You're right.  I recently simplified the formulas to remove two calls to `np.arctan2`.  But that simplification ignored possible zero-divisions — which your example runs into.  I've just reverted the formulas.  Thanks again.
