### ISSUE TITLE
From rotation matrix to quaternion and then back from quaternion to rotation matrix

### ISSUE THREAD

**Issue by prince2110** [moble/quaternion#129]
I am new to programming and I am unable to figure out if I am doing something wrong or if there is a problem. 

In the program below I am defining a rotation matrix and the making a quaternion out of it. Then I am trying to transform the same quaternion back to rotation matrix. I am getting different rotation matrices. I think both should have been the same. Please Help !!

```python
>>> import quaternion
>>> import numpy as np
>>> rotation_matrix_array = np.array([[ 0.81605268, -0.02692015,  0.57735027], 
                                      [-0.43133988, -0.69326227,  0.57735027], 
                                      [-0.64886895, -0.49561654,  0.57735027]])
>>> quaternion_quat = quaternion.from_rotation_matrix(rotation_matrix_array)
>>> rotation = quaternion.as_rotation_matrix(quaternion_quat)
>>> rotation
array([[ 8.31671186e-01, -1.80696856e-01,  5.25044459e-01],
       [-5.13073994e-01,  1.11475381e-01,  8.51074800e-01],
       [-2.12316072e-01, -9.77201047e-01,  4.30094471e-09]])
>>> 
```

**Comment by moble** [comment]
Hi @prince2110.  Welcome to programming!  It looks like you're off to a pretty good start, but just making one little mistake.  It's reasonable — but not quite right — to expect that combining `from_rotation_matrix` and `as_rotation_matrix` should result in output that's the same as the input.

One of the biggest benefits of using quaternions is that it's really easy to make sure that you're actually performing a *rotation*.  In particular, you're using four numbers to represent a rotation that is fundamentally just three dimensional — which leaves you with one constraint to satisfy if you want the quaternion to represent a rotation.  Specifically, you just need to make sure that the sum of the squares of the components is 1, which you can achieve by dividing by the square root of the sum of the squares.

On the other hand, when using matrices, you're using nine numbers to represent something that's fundamentally just three-dimensional, so you're going to have a whole bunch of constraints that must be satisfied if you want your matrix to actually represent a rotation.  In particular, you need the matrix to be [orthogonal](https://en.wikipedia.org/wiki/Orthogonal_matrix).  You can check that the matrix you entered is *not* orthogonal by computing

```python
>>> rotation_matrix_array @ rotation_matrix_array.T                                                                                                                               
array([[ 1.00000001e+00, -6.49806492e-09, -1.82835840e-01],
       [-6.49806492e-09,  1.00000000e+00,  9.56808637e-01],
       [-1.82835840e-01,  9.56808637e-01,  1.00000000e+00]])
```

The fact that this is not (at least pretty close to) the identity matrix means that your `rotation_matrix_array` is pretty far from orthogonal.

Now, the `from_rotation_matrix` function was actually designed with the expectation that any input it gets won't be perfectly orthogonal, so it essentially finds the *orthogonal* matrix that is *closest to* the input matrix (sometimes called the ["Orthogonal Procrustes problem"](https://en.wikipedia.org/wiki/Orthogonal_Procrustes_problem)), and only then finds a quaternion that achieves that rotation.  If you look at [the documentation for `rotation_matrix_array`](https://quaternion.readthedocs.io/en/latest/_autosummary/quaternion.html#quaternion.from_rotation_matrix), that's what all this talk about the Bar-Itzhack and Markley algorithms really means.

You should note that the result for `rotation` *is* very close to orthogonal:
```python
>>> rotation @ rotation.T                                                                                                                                                         
array([[ 1.00000000e+00, -2.00190821e-17, -3.64811205e-17],
       [-2.00190821e-17,  1.00000000e+00,  7.22057784e-18],
       [-3.64811205e-17,  7.22057784e-18,  1.00000000e+00]])
```
(You can generally disregard numbers that are anything less than about [2e-16](https://en.wikipedia.org/wiki/Machine_epsilon) times the largest number in your calculation.)  So now, if you "roundtrip" this orthogonal matrix through these two functions, you find that you do actually get the same result:
```python
>>> quaternion.as_rotation_matrix(quaternion.from_rotation_matrix(rotation))                                                                                                      
array([[ 8.31671186e-01, -1.80696856e-01,  5.25044459e-01],
       [-5.13073994e-01,  1.11475381e-01,  8.51074800e-01],
       [-2.12316072e-01, -9.77201047e-01,  4.30094438e-09]])
```

**Comment by prince2110** [comment]
Thanks a lot for your help. :) Based on your comment, I checked my required rotation matrix for orthogonality. Then I observed that when the determinant of my rotation matrix was -1 (which I believe is a rotation matrix for Reflection) the "from_rotation_matrix" was then also taking some other nearby orthogonal matrix. Then by multiplying my entire rotation matrix by (-1) gives the roundtrip to yield same results. Please correct me if I am wrong !!

I used the following rotation matrix:
np.array([[ 0.28817666,  0.76395083,  0.57735027],
               [ 0.5175125,  -0.63154373,  0.57735027],
               [-0.80568916, -0.13240711,  0.57735027]])
