### ISSUE TITLE
quaternion generate warning about numba being deprecated

### ISSUE THREAD

**Issue by buddyp1952** [moble/quaternion#133]
**Describe the bug**
When running our application, which uses quaternion.py, we get the following warning:
```
/usr/local/lib/python3.7/site-packages/quaternion/numba_wrapper.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
 Import requested from: 'numba.utils', please update to use 'numba.core.utils' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
   from numba.utils import IS_PY3
 /usr/local/lib/python3.7/site-packages/quaternion/numba_wrapper.py:20: UserWarning: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 Could not import from numba, which means that some
 parts of this code may run MUCH more slowly.  You
 may wish to install numba.
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**To Reproduce**
Provide a minimal code example that allows this bug to be reproduced.  If relevant, fill out the code sample below with something that demonstrates your problem.
```python
import numpy as np
import quaternion

print(quaternion.z * quaternion.x)
```
I think running that in our environment would do it

**Expected behavior**
warning free execution

**Environment (please complete the following information):**
 - OS, including version Ubuntu Linux 18.04 LTS
 - Installation method (conda, pip, or compiled from source) pip
 - Numpy version (use `np.version.version`) numpy-1.18.3-cp37-cp37m-manylinux1_x86_64.whl
 - Quaternion version (use `quaternion.__version__`) numpy-quaternion-2019.12.11.22.25.52.tar.gz
 - numba-0.49.0-cp37-cp37m-manylinux2014_x86_64.whl

**Additional context**
Thanks!

**Comment by moble** [comment]
Thanks for reporting this; it's new behavior in numba that I hadn't run into yet.  I've added a `try` statement to catch it.  The update is on pypi now (and should make its way to conda later today).  Let me know if you run into any more trouble.

**Comment by buddyp1952** [comment]
Thanks for fixing it so fast!

**Comment by bcbnz** [comment]
This fix isn't quite right -- new versions of Numba raise `ImportError` not `ModuleNotFoundError` when trying to import IS_PY3. This means the except statement you added doesn't catch it, and instead it falls through to the except on line 14 and thinks that Numba isn't available.

If you change the exception class the user still gets the Numba DeprecationWarning printed to screen. It's easiest to remove the import of IS_PY3 altogether and just use the fallback calculation, which is identical code to what old Numba versions did anyway. I've submitted a pull request doing this.
