### ISSUE TITLE
Potential bug in `squad` when using multiple dimensions.

### ISSUE THREAD

**Issue by kaufManu** [moble/quaternion#138]
**Bug description**
Related to [issue 137](https://github.com/moble/quaternion/issues/137) which I reported a few days ago. I'm not sure whether this is a bug or if I misinterpret how the function is intended to work. Assume `quats` is an array of quaternions with shape `(10, 2)`. I'm expecting that `squad(quats)[:, 0] == squad(quats[: 0])`. However, depending on the output framerate, that's not the case.

**Example**
```python
import numpy as np
import quaternion


x = np.zeros([10, 2, 4])
x[:, 0, 0] = 1.0
x[:, 1, 1] = 1.0
x = x / np.linalg.norm(x, axis=-1, keepdims=True)
quats = quaternion.from_float_array(x)

fps_in = 100
fps_out = 60

duration = quats.shape[0] / fps_in
ts_in = np.arange(0, duration, 1 / fps_in)
ts_out = np.arange(0, duration, 1 / fps_out)

quats_new = quaternion.squad(quats, ts_in, ts_out)
print(quats_new[:, 0])

quats_new2 = quaternion.squad(quats[:, 0:1], ts_in, ts_out)
print(quats_new2[:, 0])
```

The first print out of `quats_new` is very different from `quats_new2` and it seems that `quats_new` is wrong. Note that this does not happen when `fps_in` is a multiple of `fps_out`. E.g. change `fps_out` to 50 and it works as expected.

**Environment**
 - Windows 10
 - Installation method: pip
 - Numpy version `1.18.4`
 - Quaternion version `2020.5.11.13.33.35`

**Comment by moble** [comment]
Sorry about that; I forgot to handle the extra dimensions in calls to `np.roll`, and I guess it slipped through my test.  I've added another test to catch this problem, and fixed the problem in 316aa351d2e48c145f8a08548cc053889ba82ff4, which is now on pip, and should be on conda-forge within the day.
