### ISSUE TITLE
 Symbolic quaternions

### ISSUE THREAD

**Issue by WysokiStudent** [moble/quaternion#140]
**Is your feature request related to a problem? Please describe.**
I would like to use this implementation of quaternions with sympy. The reason is that sympy's implementation of a quaternion is a little clunky.

**Describe the solution you'd like**
I would like this to be legal:
`quaternion.quaternion(sp.Symbol("w"), sp.Symbol("x"), sp.Symbol("y"), sp.Symbol("z"))`
Currently this gives an error:
`quaternion constructor takes zero, one, three, or four float arguments, or a single quaternion`

**Describe alternatives you've considered**
I considered using sympy[ orienter classes](https://docs.sympy.org/latest/modules/vector/api/orienterclasses.html#quaternionorienter) and implementing quaternions by copying and modifying code from [stackoverflow](https://stackoverflow.com/a/4870905/13559733).

**Additional context**
What needs to be changed to make this possible?

**Comment by moble** [comment]
Unfortunately, this would require a complete rewrite of the code.  This code is designed to be fast numerically, and is tailored for numpy — and even coded directly in C, which means I can't directly reuse the code for anything else in python.  I do plan to rewrite the code at some point to make use of newer features in python that would enable some of that code reuse, while retaining fast numerics, but it won't happen very soon.

However, note that sympy actually has another, more complete, class for quaternions in `sympy.algebras`.  (I think it was introduced in sympy version 1.2.)  Here's some simple code showing how it works:
```python
import sympy
from sympy.algebras import Quaternion

w, x, y, z = sympy.symbols('w, x, y, z', real=True)
q = Quaternion(w, x, y, z)

vx, vy, vz = sympy.symbols('v_x, v_y, v_z', real=True)
v = Quaternion(0, vx, vy, vz)

vprime = q * v * q.conjugate()

```
It has the basic features, including the `exp` function.  And it uses conventions that appear to be compatible with the conventions in this package.

**Comment by moble** [comment]
Also, please note that this package's source code is available under an MIT license, meaning you can reuse it pretty freely.  There's a lot of python code in [the init file](https://github.com/moble/quaternion/blob/master/__init__.py) for some things like converting to/from rotation matrices.  Most of that code should be easy to modify for use with your own classes.  All the basics (like multiplication, exp, log, etc.) are written in C in [this file](https://github.com/moble/quaternion/blob/master/quaternion.c) and [this file](https://github.com/moble/quaternion/blob/master/quaternion.h), which makes them a little harder to modify, but they're simple enough that you should be able to use anything you find if you need it.
