### ISSUE TITLE
Stop Numba/Scipy installing as dependencies in pipenv

### ISSUE THREAD

**Issue by nvonahsen** [moble/quaternion#152]
I am deliberately using quaternion without installing scipy/numba as I am constrained to a limited package size, and with the features I am using I have found little performance improvement from using them

I manage my packages with pipenv which automatically installs the Numba and Scipy dependencies. I have noticed this only since the September 3rd 2020 release, before this these packages were not installed by default.
I would assume this is due to the changes to setup.py from August 25th

If possible without causing issues elsewhere in the project it would be great if installation of these packages was not done by default.

For now I have simply moved back to version 2020.5.19.15.27.24 which seems to be the last one without this problem.
Unfortunately I am locked into using pipenv as this is for a client project and so cannot switch to conda which I imagine may not have this issue.

**Comment by moble** [comment]
Sorry about that.  I think I was worried about getting the environment markers working in `setup.py`, and forgot that those had been optional.  I'll try to make them extras.
