### ISSUE TITLE
import quaternion fails on Windows

### ISSUE THREAD

**Issue by resident12** [moble/quaternion#154]
python3 -m pip install numpy-quaternion
or
conda install -c conda-forge quaternion

quaternion         conda-forge/win-64::quaternion-2020.9.5.14.42.2-py37h3a3b6f7_1

Both create a directory \Lib\site-packages\Quaternion whereupon import quaternion fails. Renaming to \Lib\site-packages\quaternion solves the issue.

**Comment by moble** [comment]
I'm afraid I can't really help with this.  I've never seen this before, and there's not much information here.  This would seem to be (in decreasing order of likelihood) a problem with (1) your specific installation of python, (2) your specific machine, or (3) Windows.  I don't have access to Windows machines, except through github actions, which work as expected.

My best guess would be that you installed the "Quaternion" package with pip — which is a very old, unmaintained, and unrelated package — and somehow the paths got mixed up.

**Comment by moble** [comment]
I've run [a test on Github Actions](https://github.com/moble/quaternion/actions/runs/404442767) that just tries a fresh install on windows.  It runs a separate job for each version of python that's currently supported, and a separate job for pip and for conda.  For each job, it runs in a fresh Windows container, sets up the most basic miniconda or python+pip environment it can, then installs as suggested in the README.  And in all cases, everything works just as expected.  

I conclude that this must be a problem with your python installation.  See my response to the related (but different) issue #155.

**Comment by risa2000** [comment]
Just to confirm the same problem happened for me. I installed `quaternion` package, while believing that I was installing `numpy-quaternion`.  When I realized this was not the right package, I installed `numpy-quaternion` as well and got the packages into a state where `import quaternion` was failing. I guess the problem might be in Windows treating `Quaternion` and `quaternion` as the same folders.
