### ISSUE TITLE
Quaternion representation order

### ISSUE THREAD

**Issue by johnwlambert** [moble/quaternion#168]
Hi @moble -- I couldn't find if your library represents quaternions as scalar-first or scalar-last

qw, qx, qy, qz

or 

qx, qy, qz, qw

Would you mind adding that to the documentation, or pointing me to where it's explained? Thanks

**Comment by moble** [comment]
Huh!  All these years, and I don't think anyone has ever asked that before.

It's the first option: `qw, qx, qy, qz`.

I'll add some documentation about it.
