### ISSUE TITLE
"Could not import from numba" warning always present

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [moble/quaternion#175]
I have seen [two places](https://github.com/moble/quaternion/search?q=Could+not+import+from+numba) where it is checked if `numba` can be imported and a warning printed if not, but don't understand why I see it because `numba` is available, and I can use it.

I see this even if I have the following script:

```python
if __name__ == "__main__":
    import quaternion
    a = quaternion.from_float_array([1., 2., 3., 0.])
    print(a)
```
output:
```bash
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Could not import from numba, which means that some
parts of this code may run MUCH more slowly.  You
may wish to install numba.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  warnings.warn(warning_text)
quaternion(1, 2, 3, 0)
```

---------

Checking that `numba` itself works fine:

```python
if __name__ == "__main__":

    ## Allow the code to function without numba, but discourage it
    try:
        from numba import njit, jit, vectorize, int64, float64, complex128
        GOT_NUMBA = True
    except ImportError:
        GOT_NUMBA = False

    print(f"Imported numba: {GOT_NUMBA}")

## Terminal output:
# Imported numba: True
```

Is this a known phenomenon, and is there something I could be doing wrong in my project setup?

I haven't gone as far yet as to add print statements or benchmark things to see if `numba` is actually used - if you have a quick way that will prove that either way, I can give it a go - I can successfully run all unit tests locally, if that helps.

**Comment by moble** [comment]
I've never seen this before, and cannot reproduce this behavior.  My guess is that you're somehow using different versions of python in the two cases, and only the second has `numba` installed.  Do your scripts have different [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) lines?  Are you calling the scripts with different command lines?

Just to be sure, I'd change the relevant lines in your scripts to both read
```python
if __name__ == "__main__":
    import sys
    print(sys.executable)
```
and ensure that the output is the same.

**Comment by Nicholas-Mitchell** [comment]
Ok, I found the problem - it is a version mismatch.

I still have this line in `numba_wrapper.py`:

```python
from numba.utils import IS_PY3
```

which fails on my version of `numba`.

Thanks for your response @moble  :)
