### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by ShantanuKodgirwar** [moble/quaternion#176]
The error goes away and the file is compiled by downgrading numpy from 1.21 to 1.20

**Comment by moble** [comment]
This is a known problem with numpy and python's packaging behavior, not this package.  You would have run into problems using numpy even if you hadn't tried to use this package.

Fortunately, the solution is usually pretty easy: you just have to reinstall numpy.  If you're using pip, you'll need to do this:

```bash
python -m pip install --upgrade --force-reinstall numpy
```
