### ISSUE TITLE
`np.typeDict` is deprecated

### ISSUE THREAD

**Issue by szsdk** [moble/quaternion#180]
https://github.com/moble/quaternion/blob/49dab9339317f2f815d148a950ccc5fcbe42ef57/src/quaternion/__init__.py#L44
`np.typeDict` is a deprecated alias for `np.sctypeDict`.

**Comment by moble** [comment]
Wow!  It's been deprecated for 14 years, and yet I've never seen `sctypeDict`, and as recently as a few months ago, the numpy devs themselves were talking about `typeDict` in my conversations with them — but no mention of `sctypeDict`.  Bizarre!

Thanks for the report.
