### ISSUE TITLE
Error while running quaternion.as_rotation_matrix

### ISSUE THREAD

**Issue by rakshith95** [moble/quaternion#196]
**Description**
When I try quaternion.as_rotation_matrix(q) , I get the error that the norm does not support the input types, which seems weird since quaternions are most likely going to be an array of floats. 
I tried with the types np.float64, np.float32, and np.float16 all of which produce this error.

TypeError: ufunc 'norm' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**To Reproduce**

```python
import numpy as np
import quaternion
q = np.asarray([  0.2849489 , 0.28462084, -0.64685006,  0.64759563])
R = quaternion.as_rotation_matrix(q)
```

**Expected behavior**
Returns the 3x3 Rotation matrix corresponding to the quaternion

**Environment (please complete the following information):**
 - Ubuntu 20.04
 - Installation method:  pip
 - Numpy version: '1.21.5'
 - Quaternion version: '2022.2.10.14.20.39'

**Comment by moble** [comment]
The `quaternion.as_*` functions take *quaternion* arrays, not *float* arrays.  You could just use
```python
q = quaternion.as_quat_array([  0.2849489 , 0.28462084, -0.64685006,  0.64759563])
```
