### ISSUE TITLE
Inplace multiplication crashes interpreter

### ISSUE THREAD

**Issue by hovren** [moble/quaternion#20]
Multiple inline multiplications of single quaternions crashes the interpreter.

Minimal test case:

    q0 = np.quaternion(1, 0, 0, 0)
    q1 = np.quaternion(0, 0, 0, 0)
    for i in range(10):
        q0 *= q1

This does not happen with `q0 = q0 * q1` or if `q0` and `q1` are quaternion *arrays* instead of single quaternions.

My version is 2015.11.06.dev83a0f48 installed using conda

**Comment by moble** [comment]
As noted in the commit message, the inplace operators were apparently `Py_DECREF`ing, which I can't find documented anywhere, and makes no sense to me.  But I've checked that manually `Py_INCREF`ing doesn't lead to a memory leak in either python 2.7 or 3.5.  I also no longer get any sort of error or crash, even when running the loop 10,000 times, so I'm satisfied.
