### ISSUE TITLE
Documentation is not clear

### ISSUE THREAD

**Issue by oleg-alexandrov** [moble/quaternion#202]
Thank you for the nice quaternions package. The documentation needs some work though. It was not clear from the doc at  https://quaternion.readthedocs.io/en/latest/ how to use the function "as_rotation_matrix". The correct usage is:

M = quaternion.as_rotation_matrix(q)

I know it looks obvious in retrospect, but it would really great if specific code snippets are added, both for this, and for "from_rotation_matrix", rather than counting on the user to read the whole page a few times and intuit what the general conventions may be.  I had to search around in order to figure this out.

**Comment by moble** [comment]
I don't understand how you're suggestion is any more extensive than [the existing documentation for that function](https://quaternion.readthedocs.io/en/latest/Package%20API%3A/quaternion/#as_rotation_matrix), but pull requests are welcome.

**Comment by oleg-alexandrov** [comment]
The main page does not link to that documentation, that's why. :)
