### ISSUE TITLE
half integer ell

### ISSUE THREAD

**Issue by gdurkin** [moble/quaternion#21]
So I am using this code to generate Wigner rotation matrices quickly -- but when I rotate a normalized ket with the matrix derived in this way it produces a new ket with the wrong normalization IF the ket is a half integer spin ket, e.g. a qubit or spin 3/2 particle. (everything is fine when the state has integer spin, ell = 1,2,3,..)

am i missing the code for the half-integer case?

**Comment by moble** [comment]
You're not using *this* code to generate Wigner rotation matrices.  Are you talking about [this](https://github.com/moble/spherical_functions) code?

**Comment by gdurkin** [comment]
Thanks for the quick reply, I was using:

import quaternion
import spherical_functions as sf

def QuaternionRotMat(ell,aa,bb,cc,dd):
    indices = []
    R = np.quaternion(aa,bb,cc,dd).normalized()
    indices = np.array([[ell,mp,m]
                    for mp in np.arange(-ell, ell + 1) for m in
np.arange(-ell, ell+ 1)])
    mat = sf.Wigner_D_element(R, indices).reshape((2*ell + 1, 2*ell + 1))
    return mat

On 20 January 2016 at 17:04, Mike Boyle <notifications@github.com> wrote:

> You're not using *this* code to generate Wigner rotation matrices. Are
> you talking about this <https://github.com/moble/spherical_functions>
> code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moble/quaternion/issues/21#issuecomment-173417540>.
>



-- 
Dr. Gabriel A. Durkin,
Senior Research Scientist
SGT, Inc.
and
Quantum Artificial Intelligence Laboratory (QuAIL)
at
NASA Ames Research Center
Moffett Field
CA 94035
USA
Tel: +1 626 993 4132
Email: gabriel.durkin@qubit.org
Web: http://www.nas.nasa.gov/quantum/durkin.html
<http://www.nasa.gov/centers/ames/research/qpl/durkin-index.html>
NASA QFT 1.0 Conference: http://quantum.nasa.gov

**Comment by moble** [comment]
This issue was moved to moble/spherical_functions#17

**Comment by moble** [comment]
This is an issue with the `spherical_functions` package, so I used [the issue mover](https://github-issue-mover.appspot.com/) to move it there.

**Comment by gdurkin** [comment]
ok jolly good

On 20 January 2016 at 20:11, Mike Boyle <notifications@github.com> wrote:

> This is an issue with the spherical_functions package, so I used the
> issue mover <https://github-issue-mover.appspot.com/> to move it there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moble/quaternion/issues/21#issuecomment-173446110>.
>



-- 
Dr. Gabriel A. Durkin,
Senior Research Scientist
SGT, Inc.
and
Quantum Artificial Intelligence Laboratory (QuAIL)
at
NASA Ames Research Center
Moffett Field
CA 94035
USA
Tel: +1 626 993 4132
Email: gabriel.durkin@qubit.org
Web: http://www.nas.nasa.gov/quantum/durkin.html
<http://www.nasa.gov/centers/ames/research/qpl/durkin-index.html>
NASA QFT 1.0 Conference: http://quantum.nasa.gov
