### ISSUE TITLE
Version number of latest release

### ISSUE THREAD

**Issue by bcbnz** [moble/quaternion#213]
The release made yesterday (automated with 7113a90) is numbered v2022.4.3 (both on GitHub and PyPI) -- was this intended to be v2023.2.1? Possibly a bug in the way the automation increments the version number?

**Comment by moble** [comment]
No, I used to use [CalVer](https://calver.org/) just out of laziness.  But then I needed to issue some breaking changes, and saw the error of my ways: CalVer makes sense for some projects, but not any of mine.  So now I've switched to SemVer.  But I can't reduce the major numbers back to sensible values without breaking SemVer, so I'm stuck with these ugly things.  🤷
