### ISSUE TITLE
add from_euler_angles equivalent for Tait-Bryan angles

### ISSUE THREAD

**Issue by petaflot** [moble/quaternion#217]
from_euler_angles() is supposed to make my life easier, it's actually confusing me.

I would be grateful to have a from_taitbryan_angles() function that does just what its name says.

**Comment by moble** [comment]
I think you need to reread [this section](https://github.com/moble/quaternion/wiki/Euler-angles-are-horrible#conventions).  Calling something "Tait-Bryan" doesn't make it any clearer; Wikipedia only claims that [that narrows it down to a group of six possible conventions](https://en.wikipedia.org/wiki/Euler_angles#Chained_rotations_equivalence), but even that assumes a bunch of other conventions that somebody will come here to complain at me about.

***The only unambiguous definition that is possible is to write down the quaternion that will be output in terms of the input arguments.***  And that is exactly what the docstring does when it says
```python
R = exp(alpha*z/2) * exp(beta*y/2) * exp(gamma*z/2)
```
How you interpret that quaternion as a rotation is up to you.  How you apply such a rotation is up to you, and different people make different choices.  So there is no possible way for one person to explain these to anyone else that is unambiguous.  ***You have to do the math for yourself to see what you want to do.***

These are the sorts of explanations that my page about Euler angles was supposed to make unnecessary for me to write.  If you don't like it, feel free to write your own function, like
```python
def my_personal_idea_of_what_euler_angles_should_be(alpha, beta, gamma):
    return np.exp(alpha*quaternion.x/2) * np.exp(beta*quaternion.y/2) * np.exp(gamma*quaternion.z/2)
```
