### ISSUE TITLE
FTBFS on Windows with MSVC++ 9

### ISSUE THREAD

**Issue by rhymoid** [moble/quaternion#23]
Since `quaternion.h` looks for `_MSC_VER`, I assume that MSVC++ is an intended target for this package. However, after installing "Microsoft Visual C++ Compiler for Python 2.7" and invoking

    pip install git+git://github.com/moble/quaternion

the build phase fails due to various problems that may be unique to MSVC++:

* The `<math.h>` functions `isnan`, `isinf`, and `isfinite` are apparently not available in `quaternion.h`.
* The C99 compound literal syntax (e.g. `(quaternion) { w, x, y, z }`) is not supported by MSVC++.

**Comment by moble** [comment]
I simply copied that `_MSC_VER` line from an older package that added quaternions to numpy.  I have no access to any computers running Windows, so I can't really be of any help in solving these problems or testing to see if they work on Windows.  But I'd be happy to incorporate any changes you can suggest, as long as they don't break things on other platforms.
