### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by arsenovic** [moble/quaternion#27]
install from conda fails, 

```
> conda install -c moble quaternion
Fetching package metadata ....Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://co
nda.anaconda.org/moble/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/ar-74969af3-431a-426e-8ecb-75efaa76452b/m
oble/noarch/repodata.json)Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.
anaconda.org/moble/linux-64/,
```

**Comment by moble** [comment]
Hrm.  I can't reproduce this, even on a brand new machine.  (I had never logged in before.  I didn't even have a `.bashrc`; I just installed anaconda, and ran `conda install -c moble quaternion`.)  I wonder if it's related to [this issue (having a `.netrc` file](https://github.com/Anaconda-Platform/support/issues/23)???

**Comment by arsenovic** [comment]
strange. .. 
i dont have a .netrc file in pwd or in  my home/.  not sure. i got it through pip though.
