### ISSUE TITLE
Vetorized slerp

### ISSUE THREAD

**Issue by javidcf** [moble/quaternion#28]
Is there anyway to run a vectorized form of `quaternion.slerp`? I have not been able to get this behavior even using `numpy.frompyfunc` or `numpy.vectorize` (which, on NumPy's own words, are more of "convenience functions" than actual performance boosters, but anyway), since I keep getting this `ValueError: No cast function available.`.
*Edit:* Just in case it's not clear, I'm talking about the possibility of having, say, 100 start quaternions, 100 end quaternions and 100 alpha values and make the 100 interpolations in one step (or, also, using broadcasting rules, like just two quaternion and 100 alpha values, etc.)

**Comment by moble** [comment]
I've just added some relevant functions.  Probably the easiest to use is `quaternion.slerp`.  That's just a thin wrapper around `np.slerp_vectorized`, and automatically normalizes the time.  I think they should give you what you need; if not, just let me know and we can reopen this issue.

Also note that there are `squad` functions, if you have more than two quaternions you need to interpolate between.
