### ISSUE TITLE
quaternion.py library function won't work

### ISSUE THREAD

**Issue by rosana0331** [moble/quaternion#30]
I am creating a function that does some math, creates an array, and ultimately transforms that array into a a quaternion. I was doing this using brute force, but I found out the library supports that transformation by using the command: 

a = some 1x4 array
q = quaternion.as_quat_array(a)

When I use that command on my workspace, it works fine. If I try to code that up in my function, I get the following error: 

AttributeError: 'list' object has no attribute 'dtype'

Follow a screen shot:
![capture](https://cloud.githubusercontent.com/assets/22457243/19870379/aaa9f93a-9f86-11e6-92a8-13413c9db150.PNG)

I am not versed in Python and not very knowledgeable in command line.  I only know some basics. I appreciate your help!

**Comment by rosana0331** [comment]
Ok, I worked this out a little bit and found out that I had to create my lists by using np.array() command. Once I had done that, the quaternion.as_quat_array() worked just fine. Just wanted to follow up on that. thanks anyway.

**Comment by moble** [comment]
You found the right solution, but the function should have accepted a list as input, too.  So I've modified it to do so.  Thanks for pointing this out.
