### ISSUE TITLE
Can't see the list of functions available in quaternion.py

### ISSUE THREAD

**Issue by rosana0331** [moble/quaternion#31]
Hi,

I am using  the quaternion.py library in my Python 3, together with the Anaconda package. I can't see the list of functions that are available in the quaternion library when I call it in my Anaconda. Follow a screen shot below. I am showing that when I call the quaternion library it will open a window with all the available functions in it, but when I call np.quaternion it won't show anything. If I call it as only quaternion.() (without the np. in front) it will show me functions, but they are different than when you call np.quaternion.() My friend, however, (who uses python 2.7) can see the functions by calling np.quaternion.(), and I am attaching his screen shot as well for reference. I hope it's not confusing! I have already tried to reinstall everything and it didn't help. I installed my quaternion library by going directly into my python's folder and commanding 'python setup.py install'. I can use all the functions, just can't see what's available on my screen. I hope you can help me! Thank you once again!

The screen shot below shows my functions when I call quaternion.()
![capture1](https://cloud.githubusercontent.com/assets/22457243/19892656/5695f7fe-a01c-11e6-9a79-62ebaca8f395.PNG)

The screen shot below shows that I cannot see the functions when I call np.quaternion.()
![capture](https://cloud.githubusercontent.com/assets/22457243/19892816/2a5759f2-a01d-11e6-90c0-cda62b413367.PNG)

Finally, the screen shot below shows my friend's screen shot, where he calls np.quaternion.() and are able to see all the functions:
![capture2](https://cloud.githubusercontent.com/assets/22457243/19892837/3f901bd8-a01d-11e6-8deb-e30af2d640c3.PNG)

Rosana

**Comment by moble** [comment]
This isn't an issue with this `quaternion` package; it must be something wrong with your ipython installation, or with how you've imported the modules.  Does `np.q` tab-complete to `np.quaternion`?  Did you actually `import numpy as np`?  Have you noticed other problems with tab-completion?

Anyway, I've verified that this works for me (in anaconda) with both python 2 and python 3, and nothing in this package has anything to do with completion.  So I'm afraid I can't help.

**Comment by rosana0331** [comment]
I see. Yes, I have imported numpy as np and all the other libraries I use give me the tab-completion. I have already tried to re-install Anaconda twice, without success. Do you know which file in the installation package for the quaternion library would give me the functions, if there is a one-file I can look at? Thanks for double-checking this issue in your pythons 2 and 3 and for trying to help me out.

Rosana

**Comment by moble** [comment]
The functions are not all listed in any one file, but if you do `dir(quaternion)` and `dir(np.quaternion)`, you should be able to see them.  Note that you probably want to ignore anything that starts with one or more underscores.

**Comment by rosana0331** [comment]
Sounds good! Thank you!
