### ISSUE TITLE
Quaternion division

### ISSUE THREAD

**Issue by rosana0331** [moble/quaternion#32]
Does anyone know how to use the division function? I am trying to use it as:
q1 = something
q2 = something else
div = quaternion.division(q2,q1)

Is that correct? I can't find any examples for this particular library. Thank you!

**Comment by moble** [comment]
Just use `/` as you would for numbers:
```python
import numpy as np
import quaternion
q1 = quaternion.x
q2 = quaternion.y
q1/q2
```

**Comment by rosana0331** [comment]
Perfect. Thank you!

**Comment by rosana0331** [comment]
Thank you!


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Mike Boyle <notifications@github.com> Date: 11/2/16  11:32 AM  (GMT-05:00) To: moble/quaternion <quaternion@noreply.github.com> Cc: rosana0331 <rb0331@twc.com>, Author <author@noreply.github.com> Subject: Re: [moble/quaternion] Quaternion division (#32) 
Just use / as you would for numbers:

import numpy as np
import quaternion
q1 = quaternion.x
q2 = quaternion.y
q1/q2

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/moble/quaternion","title":"moble/quaternion","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/moble/quaternion"}},"updates":{"snippets":[{"icon":"PERSON","message":"@moble in #32: Just use `/` as you would for numbers:\r\n```python\r\nimport numpy as np\r\nimport quaternion\r\nq1 = quaternion.x\r\nq2 = quaternion.y\r\nq1/q2\r\n```\r\n"}],"action":{"name":"View Issue","url":"https://github.com/moble/quaternion/issues/32#issuecomment-257901232"}}}
