### ISSUE TITLE
Spherical Functions examples

### ISSUE THREAD

**Issue by mrollins** [moble/quaternion#33]
The two examples on the Spherical Functions documentation page incorrectly place the `quaternion` module inside the `np` namespace:

```
>>> import numpy as np, quaternion
>>> vartheta, varphi = 0.1, 0.2
>>> R_tp = np.quaternion.from_spherical_coords(vartheta, varphi)
```

```
>>> import numpy as np, quaternion
>>> alpha, beta, gamma = 0.1, 0.2, 0.3
>>> R_euler = np.quaternion.from_euler_angles(alpha, beta, gamma)
```

The last line of these code snippets should reference `quaternion.from_*`, rather than `np.quaternion.from_*`

**Comment by moble** [comment]
I can't actually find that code anywhere either [in this repository](https://github.com/moble/quaternion/search?utf8=%E2%9C%93&q=np.quaternion.from_spherical_coords&type=Code) or [in the `spherical_functions` repository](https://github.com/moble/spherical_functions/search?utf8=%E2%9C%93&q=np.quaternion.from_spherical_coords&type=Code).  Are you sure you're working from current versions?  Some of the functions that are now in `quaternion` were indeed previously found under `np.quaternion`, so maybe you're looking at an old version.  If not, could you be more specific?

**Comment by mrollins** [comment]
The examples I refer to are located on [this page](http://moble.github.io/spherical_functions/#euler-angles) linked in the README. Unfortunately, I was unable to find the source of this web page either.

**Comment by moble** [comment]
I see.  Those are [github pages](https://pages.github.com/), which are stored in [the `gh-pages` branch of `spherical_functions`](https://github.com/moble/spherical_functions/tree/gh-pages), and are apparently not searched through the github search bar.  I've corrected them now.  Thanks for pointing this out.
