### ISSUE TITLE
as_quat_array is not working for huge volume of data:

### ISSUE THREAD

**Issue by Srinivsankrishnan27** [moble/quaternion#35]
When I tried to convert numpy array of size (2510792,4) to quaternion, I am not able to do the same. But the functionality is working for small size arrays

**Comment by moble** [comment]
It works for me — even for arrays hundreds of times bigger than that, which is several gigabytes.  If you want me to help solving your problem, I really need more information, like a minimal example that reproduces your error, and the error message you get when you try to run it.

**Comment by Srinivsankrishnan27** [comment]
Thanks for the mail,

The problem occurs if I load a data from pandas data frame by using
df.values.

**Comment by moble** [comment]
Again, I'd be happy to try to help you with this, but I can't help unless you give me a *minimal* example that results in error for you, and the actual error output that you're seeing.  For instance, I tried this example, which worked just fine:

```python
import numpy as np
import quaternion
import pandas as pd

df = pd.DataFrame(np.random.rand(2510792, 4))
q = quaternion.as_quat_array(df.values)
```

And again, I can increase that to be hundreds of times bigger without any problem.

**Comment by Srinivsankrishnan27** [comment]
​
 delq.pkl
<https://drive.google.com/a/connectedlife.io/file/d/0ByOE4PDw6_LrMmJGWXdYNVY0cTQ/view?usp=drive_web>
Hi,

Thanks for the mail.

Sorry for the inconvenience, will explain you with an example. Herewith
attached the screenshots which explain the scenarios clearly.

Attached the pickle file for your reference, you can load into the
dataframe to test the scenario. Please let me know if you need more
information on the same. You can give me call at any time regarding this
issue.


Thanks and Regards
Srinivasan T
call me @: 91210410

**Comment by moble** [comment]
I don't see any screenshots, and I really can't help if you don't tell me what the error is.  Maybe you should go to this issue's github page to add the information.

**Comment by Srinivsankrishnan27** [comment]
I have updated the comments and uploaded the screenshots, I didn't receive any receive any error message, the issue the function is not working as expected.

**Comment by moble** [comment]
I cannot see the screenshots.  Please go to this issue's github page https://github.com/moble/quaternion/issues/35 and see for yourself.  There are no screenshots.  You need to show me what is going on, or I cannot help you.

**Comment by Srinivsankrishnan27** [comment]
I have compiled all the screen shots as a msword file and attached. Attaching again.
[quatissue.docx](https://github.com/moble/quaternion/files/691863/quatissue.docx)

**Comment by moble** [comment]
This is getting a little ridiculous.  I do not have MS Word, and I cannot open `docx` files.  No offense, but I do not know you, and will not trust attachments you attempt to give me.

The standard way of working on github is to go to [the issues page](https://github.com/moble/quaternion/issues/35), then copy and paste whatever you need into the comment editor provided on that page.  It is possible to drag and drop images, though it's better to use text if the image is of text.  Please, please, please just do that.  If you cannot work in this way, I'm afraid I will be unable to help you.

**Comment by Srinivsankrishnan27** [comment]
Sorry I am new to gitHub, thats why I attaching as a docx file. will paste my all screenshots over here,
![image](https://cloud.githubusercontent.com/assets/22492104/21747139/a0e887b6-d598-11e6-8b1c-bb020a39f0e6.png)
![image](https://cloud.githubusercontent.com/assets/22492104/21747141/a7178f24-d598-11e6-8a82-c6432ae55c74.png)
![image](https://cloud.githubusercontent.com/assets/22492104/21747142/ac27cfd8-d598-11e6-9382-b0faf136b3cf.png)
![image](https://cloud.githubusercontent.com/assets/22492104/21747143/b25895ae-d598-11e6-9b68-3bce782002c8.png)
![image](https://cloud.githubusercontent.com/assets/22492104/21747144/b59b8410-d598-11e6-9e05-e88182103f80.png)
![image](https://cloud.githubusercontent.com/assets/22492104/21747145/bcb3b484-d598-11e6-8af5-7b7a8062b5ab.png)


I am trying to load this dataframe values into quaternion array using df.values

import numpy as np
import quaternion as quat
import pandas as pd
del_q =  quat.as_quat_array(myquats.values)

as_quat_array works fine but the problem is its working in other way.
From the first few screenshots we know that the first quaternion set is to quaternion(1,0,0,0) but here its quaternion(1,1,1,1).


But if I use the same ‘quat.as_quat_array’ for some reduced length I am to convert it as a quaternion array.
For eg:
del_q =  quat.as_quat_array(myquats[:20000].values)
here I am converting first 20000 values
In this case the function works as expected.

**Comment by moble** [comment]
I think I've figured it out, but this still really isn't enough information to definitively diagnose your problem.  Next time you ask for help with someone else's code, you need to think about how they could possibly understand your problem; you should include a [minimal working example](https://en.wikipedia.org/wiki/Minimal_Working_Example) that shows what you've done, and describe exactly what's going wrong.  That is, you need to give them code that allows them to reproduce your problem with as little difficulty as possible, and then explain exactly in what way the result isn't what you expected.  Screenshots are not good enough, and they shouldn't have to ask you numerous times to give them basic information like that when they're doing you a favor.  Also, you shouldn't expect people to be willing to open random files (like `docx` or `pkl`) that you post on the internet; you may be a nice guy, but they have no way of knowing that you're not trying to hack their computer.  (Note that the `pickle` module contains a [warning at the very top of the page against opening pickles from untrusted sources](https://docs.python.org/3/library/pickle.html).)

Anyway, somehow you appear to have created a pandas array with Fortran ordering.  I cannot figure out how you might have done this, but you can probably solve the problem by doing this:
```python
del_q = quat.as_quat_array(np.ascontiguousarray(myquats.values))
```
I've added this `ascontiguousarray` call inside the `as_quat_array`, but it will take a little while for anaconda and pypi to update the package.  So for now, just call that function yourself.

**Comment by Srinivsankrishnan27** [comment]
It's working like a charm, thanks for the help.

Since I am very new to this forum, I don't know about how the report the issue. Sorry for the inconvenience caused. I would take this as an opportunity to learn how to post an issue in gitHub.
