### ISSUE TITLE
Installation issue with python 2.7

### ISSUE THREAD

**Issue by bscalzo** [moble/quaternion#43]
I currently have anaconda with python 2.7 on my PC. 
I've tried to install the package using 

conda install -c moble quaternion

but this leads to the following error:

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 2.7*
  - quaternion -> python 3.5*
Use "conda info <package>" to see the dependencies for each package.

Does the package not work with python 2.7 alone?

Many thanks.

**Comment by moble** [comment]
When you say "PC" I'm guessing you mean Windows.  Is that right?  The conda build on windows is broken; it uses appveyor, which does not particularly support python/conda.  And I don't have access to any Windows machines, so I can't do it myself.  I'll add a note to the README saying that conda isn't really supported on Windows.

But you should be able to do it with

```bash
pip install numpy numpy-quaternion
```

[Note that this should use the version of pip that exists inside conda, so it won't go installing things outside of your conda directories.]

If this fails, you'll have to just do it manually, by downloading the repository and running `python setup.py install` from inside of the directory that you get.

Let me know what works for you.

**Comment by bscalzo** [comment]
Yes I have windows. I've tried the various installation methods suggested but all of them lead to this problem:

Building msvcr library: "C:\Users\User1\AppData\Local\Continuum\Anaconda2\libs\
libmsvcr90.a" (from C:\windows\winsxs\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
9.0.21022.8_none_750b37ff97f4f68b\msvcr90.dll)
error: [Error 2] The system cannot find the file specified

I believe this has nothing to do with numpy_quaternion though.

**Comment by moble** [comment]
Yeah, unfortunately it's a C module, so it has to be compiled.  And since I can't do it, it has to be left to the user — which is apparently when things get tricky on Windows.  But that's beyond my scope.  Sorry.  The only thing I can suggest is maybe just run `conda update --all`, in case it's a bug that's been fixed.

**Comment by moble** [comment]
In issue #73, I realized what the problem is: an old conda build from when 3.6 wasn't even out yet.  I've removed all the old Windows builds, so anyone on Windows will need to install manually, or could try `pip`.  I'll mention that in the README.

**Comment by moble** [comment]
Actually, I just realized that this was already covered in the README.

**Comment by moble** [comment]
The current version is now available for Windows (and Linux and macOS) [via conda-forge](https://anaconda.org/conda-forge/quaternion)
