### ISSUE TITLE
as_float_array dimensions vary for python2 vs python3

### ISSUE THREAD

**Issue by vyasr** [moble/quaternion#46]
The following code snippet yields slightly different answers depending on whether it is run in python2 or python3:
```
>>> import quaternion as q
>>> p = q.quaternion(1, 2, 3, 4)
>>> print(q.as_float_array(p))
```
In python2:
```
[ 1.  2.  3.  4.]
```
In python3:
```
[[ 1.  2.  3.  4.]]
```
I imagine that the second behavior is preferable, but either way should be fine as long as it's consistent.

**Comment by moble** [comment]
The behavior was changed in issue #44, to go from what you list for python3 to what you list for python2.  You evidently installed the updated packaged for python2, but still have the older version for python3.  If you `print(quaternion.__version__)` it should be `2017.04.05.14.49.15.dev261789573`, which is only built for conda with python 2.7 and 3.6.  You can still install the package yourself in other versions, but not with a simple `conda install` command.
