### ISSUE TITLE
Implement isclose() for quaternion

### ISSUE THREAD

**Issue by szsdk** [moble/quaternion#47]
I was wondering if it is possible to implement np.isclose() or np.allclose() for quaternion which would be useful (especially for my project LOL).

**Comment by moble** [comment]
As stated, this is really more of an issue for numpy; I can't fix numpy code.  However, `quaternion.allclose` is implemented.  I'm not opposed to implementing `quaternion.isclose`, but I don't have time for it right now.

**Comment by moble** [comment]
However, it should be easy for you to use `quaternion.allclose` to write your own `quaternion.isclose` function.  Feel free to make a Pull Request.
