### ISSUE TITLE
unexpected behavior for imaginary part

### ISSUE THREAD

**Issue by micdao** [moble/quaternion#52]
Hi,
I found some unexpected behavior with the imaginery part of the quaternion:

```python
In [35]: a
Out[35]: quaternion(0.00277, -0.97976, -0.00186, -0.20012)

In [36]: a.real
Out[36]: 0.00277

In [37]: a.imag
Out[37]: quaternion(0, 0, 0, 0)

In [38]: np.__version__
Out[38]: '1.11.1'

In [39]: quaternion.__version__
Out[39]: '2017.01.08.dev232822920'
```
So I would expect to retrieve array_like [-0.97976, -0.00186, -0.20012]

Cheers,
Michael

**Comment by moble** [comment]
I never actually created a `.imag` function; that's apparently a numpy built-in.  I prefer the less-ambiguous `.vec`.  But I can apparently override the numpy version.

Note that to get the new version of `quaternion` from conda, you'll need to be able to get `numpy` version 1.13, which corrects a bug in `.conjugate`.
