### ISSUE TITLE
Kernel never returns from `np.prod()` on quaternions

### ISSUE THREAD

**Issue by noncom** [moble/quaternion#54]
Performing the `prod` NumPy operation over an array of quaternions results in kernel becoming unresponsive and producing a 100% CPU load. Only restarting the kernel would bring the notebook back to life.

Example code:

    np.prod([np.quaternion(1, 0, 0, 0), np.quaternion(0, 0, 0, 1)])

**Comment by moble** [comment]
I can verify that this happens with the newest versions of everything.  I've tracked it back to the `numpy.core.umath.multiply.reduce` function.  Here's a MWE:

```python
import numpy as np
from numpy.core import umath as um
import quaternion

a = np.array([quaternion.x, quaternion.y])
um.multiply.reduce(a, axis=None, dtype=None, out=None, keepdims=False)
```

Unfortunately, I can't actually find where that function is defined, because I would hope to pass the buck to the `numpy` maintainers...

@eric-wieser Since you seem to know something about both repos, any thoughts?

**Comment by eric-wieser** [comment]
`numpy\core\src\umath\ufunc_object.c:PyUFunc_Reduce` is the place to start looking. That does indeed seem odd.

However, it works fine on `np.core.test_rational.rational` - so my hunch is that your multiply inner loop is broken

**Comment by eric-wieser** [comment]
`np.multiply.reduce(a[:0])` shows the same problem, which is interesteing

**Comment by eric-wieser** [comment]
The hang is within `type_tuple_type_resolver`.

**Comment by eric-wieser** [comment]
This is a numpy bug, in `type_tuple_userloop_type_resolver`, where there is an obvious inner loop.

Please file an issue upstream!

**Comment by eric-wieser** [comment]
*infinite loop

**Comment by moble** [comment]
Thanks!  Issue filed.  I'll keep an eye on that to test any fixes, and I'll leave this open until the fix makes it into a numpy release.

**Comment by moble** [comment]
The changes have filtered down to the conda package, so this issue is resolved.  Thanks everyone!
