### ISSUE TITLE
from_rotation_matrix does not support input dimensionality > 3

### ISSUE THREAD

**Issue by kaufManu** [moble/quaternion#57]
The following snippet throws an error:

```
import numpy as np
import quaternion

quaternion.from_rotation_matrix(np.random.randn(10, 10, 3, 3))
```

> q[multi_index, 1:] = -eigvecs[:-1].flatten()
> ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,9,4)

The error does not appear when the input is three-dimensional. I also tried the same call with identity matrices (i.e. valid rotation matrices instead of random matrices), but the problem persists. The documentation explicitly states that more than 3 input dimensions can be used:

> rot: (Nx3x3) float array
>         Each 3x3 matrix represents a rotation by multiplying (from the left)
>         a column vector to produce a rotated column vector.  Note that this
>         input may actually have ndims>3; it is just assumed that the last
>         two dimensions have size 3, representing the matrix.

I am using python 3.5.2 and installed the package through conda. Version numbers: numpy 1.13.1, quaternion '2017.01.08.dev232822920'.

**Comment by moble** [comment]
Thanks for reporting this.  You are certainly correct; my code is wrong.  That `q[multi_index, 1:]` term is just totally nonsensical.

I believe I've figured out the fix.  It will take me a little while to get it tested and get the new package up on conda.  In the meantime, if you want to get on with things, you could edit the file pointed to in that error (probably something like `~/anaconda3/lib/python3.5/site-packages/quaternion/__init__.py`).  Just replace [lines 249 and 250](https://github.com/moble/quaternion/blob/132aa02e7df3cdf7175515086cbc338520f37c01/__init__.py#L249-L250) with

```python
                q[multi_index+(0,)] = eigvecs[-1]
                q[multi_index+(slice(1,None),)] = -eigvecs[:-1].flatten()
```

And let me know if you find a problem with that!  :)

**Comment by kaufManu** [comment]
@moble Wow, thanks a lot for your quick reply and the fix! Having replaced those two files solved the problem for my use cases.

Great work by the way with this package, you have saved me a lot of headaches :)
