### ISSUE TITLE
Prefered Citation

### ISSUE THREAD

**Issue by AKuederle** [moble/quaternion#59]
Hi,

I was using this package as part of my Thesis and wanted to ask if there is a preferred way to cite it (i.e. list of authors)

**Comment by moble** [comment]
The basic citation should probably be just to [this repo](https://github.com/moble/quaternion).  [Unless you're integrating angular velocity, in which case you could cite [this paper](https://link.springer.com/article/10.1007%2Fs00006-017-0793-z) (free version [here](https://arxiv.org/abs/1604.08139))].  As for the authors, I'm not picky.  You can look at the [contributions](https://github.com/moble/quaternion/graphs/contributors).  Clearly, the author list should include Michael Boyle (me!), probably Martin Ling, and possibly Stijn van Drongelen.  After that, the size of the contributions drops precipitously.  (For example, I wouldn't say that adding a single character to the documentation gets you on an author list.)  But honestly it's not a big deal; I don't think anyone will be upset with whatever you choose.

**Comment by AKuederle** [comment]
Thank you very much!
If you are interested here is a bibtex entry based on the information you provided:

```
@misc{Boyle,
abstract = {Add built-in support for quaternions to numpy},
author = {Boyle, Michael and Ling, Martin and van Drongelen, Stijn},
title = {{Quaternions in numpy}},
url = {https://github.com/moble/quaternion}
}
```

**Comment by moble** [comment]
For anyone who finds this page looking for this information, a permanent DOI and more citation information can be found here: http://doi.org/10.5281/zenodo.1220425.
