### ISSUE TITLE
Issue with integrate_angular_velocity

### ISSUE THREAD

**Issue by vikigenius** [moble/quaternion#68]
The integrate_angular_velocity does not seem to work for time intervals less than 1 second?

Especially the line https://github.com/moble/quaternion/blob/545cdb7e29d31b1d5070b1b7d041480988188229/quaternion_time_series.py#L263

Is this intended? If so how do i integrate over time-steps on the order of milliseconds?

**Comment by moble** [comment]
That line isn't the problem, it's this one:

https://github.com/moble/quaternion/blob/545cdb7e29d31b1d5070b1b7d041480988188229/quaternion_time_series.py#L192

which assumes `self._a.shape[0]` is greater than 0 to begin with.  I'll just change the initializer to ensure that's true.
