### ISSUE TITLE
formule definition for convert euler angle to quaternion

### ISSUE THREAD

**Issue by dragonlost** [moble/quaternion#71]
Hello
I'm trying to use the function "from_euler_angles ()". By cons I have a problem because it does not leave the good resustat.

For example :

from_euler_angles (0,0, np.pi / 8) = from_euler_angles (np.pi / 8,0,0) which is not true.

You use this formula : 

    R[..., 0] = np.cos(alpha/2)*np.cos(beta/2)*np.cos(gamma/2) - np.sin(alpha/2)*np.cos(beta/2)*np.sin(gamma/2)
    R[..., 1] = np.cos(alpha/2)*np.sin(beta/2)*np.sin(gamma/2) - np.sin(alpha/2)*np.sin(beta/2)*np.cos(gamma/2)
    R[..., 2] = np.cos(alpha/2)*np.sin(beta/2)*np.cos(gamma/2) + np.sin(alpha/2)*np.sin(beta/2)*np.sin(gamma/2)
    R[..., 3] = np.sin(alpha/2)*np.cos(beta/2)*np.cos(gamma/2) + np.cos(alpha/2)*np.cos(beta/2)*np.sin(gamma/2)

For X,Y, Z rotation you must use :

    R[..., 0] = np.cos(alpha/2)*np.cos(beta/2)*np.cos(gamma/2) + np.sin(alpha/2)*np.sin(beta/2)*np.sin(gamma/2)
    R[..., 1] = np.sin(alpha/2)*np.cos(beta/2)*np.cos(gamma/2) - np.cos(alpha/2)*np.sin(beta/2)*np.sin(gamma/2)
    R[..., 2] = np.cos(alpha/2)*np.sin(beta/2)*np.cos(gamma/2) + np.sin(alpha/2)*np.cos(beta/2)*np.sin(gamma/2)
    R[..., 3] = np.cos(alpha/2)*np.cos(beta/2)*np.sin(gamma/2) - np.sin(alpha/2)*np.sin(beta/2)*np.cos(gamma/2)

ref : https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19770024290.pdf

**Comment by moble** [comment]
[As the documentation clearly states](https://github.com/moble/quaternion/blob/fd23cc2b449d17508032842d3e9ef5904cb6fdbd/__init__.py#L400) this function returns 

    R = exp(alpha*z/2) * exp(beta*y/2) * exp(gamma*z/2)

which obviously corresponds to the ZYZ convention.  If you want to use your own convention, feel free to do so.  But please at least check documentation before you claim that a piece of software is wrong.
