### ISSUE TITLE
Strict python 3.5 dependency

### ISSUE THREAD

**Issue by mvy** [moble/quaternion#73]
Is this package strictly dependent on python 3.5? 

The requirements seems to advertise `python=3.5` instead of `python>=3.5` therefore I can't install it using conda in my environment.

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.6
  - quaternion -> python=3.5

```

**Comment by moble** [comment]
That requirement isn't coming from this package.  The ['requirements.txt' file](https://github.com/moble/quaternion/blob/fd23cc2b449d17508032842d3e9ef5904cb6fdbd/requirements.txt) only shows `numpy>=1.13` and `scipy`.  Meanwhile, I actually build versions specifically for python 2.7, 3.4, 3.5, and 3.6 for both Mac and Linux, as you can see [here](https://anaconda.org/moble/quaternion/files).  These are available with `conda install -c moble quaternion`.

**Comment by moble** [comment]
Ah, I just realized the problem.  You're presumably using Windows.  Somebody else reported a similar problem in #43, and they were also using Windows, which I don't support.  I did for a while, using Appveyor, but it only worked a fraction of the time and required constant attention so I dropped it a while ago.  But that meant that there were windows versions available via conda, but only old ones from when 3.6 wasn't out yet.  I've removed those now, to make sure that people aren't using old buggy versions of this package.

Instead, you'll need to try installing with `pip install numpy numpy-quaternion`, or download the code and run `python setup.py install` from the top directory.

**Comment by mvy** [comment]
I am indeed. 

Sadly distutils seems to require having a recent version of MSVC installed, which I am not prepared to maintain for such a small data treatment I want to do. The mingw32 compiler chain seems not to be fully integrated for some reason.

Thanks for the quick reply.

**Comment by mvy** [comment]
I finally got the VS2017 CE because most of the quaternion/transformation matrix extensions requires it anyway. If you know what you need to get a working binary/wheel/??, let me know if I can help with this.

**Comment by moble** [comment]
Thanks for the offer, but actually, [arsenovic suggested](https://github.com/moble/quaternion/issues/74) putting this package on conda-forge, which will build mac, linux, and windows versions.  I've just gotten it [working](https://github.com/conda-forge/staged-recipes/pull/5661), so it's ready to merge.  I'm not entirely sure how long it takes to actually get into conda-forge, but it looks like it's usually pretty quick.

**Comment by moble** [comment]
The current version is now available for Windows (and Linux and macOS) [via conda-forge](https://anaconda.org/conda-forge/quaternion).
