### ISSUE TITLE
API version issue

### ISSUE THREAD

**Issue by Shegrad** [moble/quaternion#82]
Hello,

I installed quaternion extension with following command:
conda install -c conda-foerge quaternion

When loading module I got:
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:34:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import quaternion
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramData\Anaconda2\lib\site-packages\quaternion\__init__.py", line 8, in <module>
    from .numpy_quaternion import (quaternion, _eps,
ImportError: numpy.core.multiarray failed to import

How can I fix it ?

Thank you for your help.

**Comment by moble** [comment]
As you can see, the complaint is about an old version of numpy, so try updating numpy:

    conda update numpy

**Comment by Shegrad** [comment]
I managed to fix it.
Updating with conda didn't give any improvement but pip made an update with version 14.3 and installing quaternion extension with this version works fine.
I didn't understand why using conda did not install the last version of numpy. As it works now I didn't investigate further.
I hope my feed back may help.

**Comment by moble** [comment]
Fixed by conda-forge/quaternion-feedstock#14
