### ISSUE TITLE
versions>=2018.* require numpy>=1.14

### ISSUE THREAD

**Issue by migule** [moble/quaternion#84]
**Describe the bug**
Versions >=2018* don't work with numpy==1.13.*
Requirement should be increated to numpy==1.14

**To Reproduce**
```
virtualenv venv
source venv/bin/activate
pip install numpy==1.13.3 numpy-quaternion
python -c "import quaternion"
deactivate
```

**Comment by moble** [comment]
This is fixed by e40f5eb3353dc8ee4ad9d1212d90668cc4451550.  When building, python just couldn't find the expected version of numpy; it's now correctly building against numpy 1.13.
