### ISSUE TITLE
Memory leak when multiplying or adding quaternion array

### ISSUE THREAD

**Issue by ctrlbrett** [moble/quaternion#92]
**Describe the bug**
Multiplying (and adding, haven't tried the other ops) causes a memory leak. Memory usage does not go down over time after multiplying or adding. This occurs on an older version, and on the most up to date version of the quaternion library.

**To Reproduce**
The script below will print out the memory used, you should see that  ```x = q * qa ``` consumes a ton of memory that is not reclaimed.  Running ```free``` should also show that memory is not returned until the program is killed.

Note the program below loops forever so you have time to check into its memory usage.

```python
import numpy as np
import quaternion
import tracemalloc # requires python 3.6

tracemalloc.start()

def doit():
    q = np.quaternion(0.1, 0.1, 0.1, 0.1)
    qa = quaternion.as_quat_array([1.0] * 100000000)
    x = q * qa # THIS IS THE PROBLEMATIC LINE.

def snapshot_trace():
    snapshot = tracemalloc.take_snapshot()
    top_stats = snapshot.statistics('lineno')

    print("[ Top 10 ]")
    for stat in top_stats[:10]:
        print(stat)

snapshot_trace()
doit()
snapshot_trace()
doit()
snapshot_trace()

# just here so you can check memory usage while this runs.
while True:
    pass
```
Sample output, not the first line is (1526MiB) used.

```
[ Top 10 ]
minimal.py:13: size=1526 MiB, count=4, average=381 MiB
/home/brett/miniconda3/lib/python3.6/tracemalloc.py:65: size=1584 B, count=22, average=72 B
/home/brett/miniconda3/lib/python3.6/tracemalloc.py:499: size=1488 B, count=4, average=372 B
/home/brett/miniconda3/lib/python3.6/tracemalloc.py:207: size=896 B, count=2, average=448 B
/home/brett/miniconda3/lib/python3.6/tracemalloc.py:165: size=864 B, count=2, average=432 B
/home/brett/miniconda3/lib/python3.6/tracemalloc.py:497: size=680 B, count=1, average=680 B
minimal.py:12: size=584 B, count=1, average=584 B
/home/brett/miniconda3/lib/python3.6/tracemalloc.py:469: size=528 B, count=2, average=264 B
minimal.py:18: size=480 B, count=1, average=480 B
```

**Expected behavior**
After each doit() call, memory usage should go back down and not climb as more and more calls are made, but instead we see that the memory is not reclaimed:

**Environment (please complete the following information):**
 - OS, including version:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
 - Python version: Python 3.6.3 :: Anaconda, Inc.
 - Installation method: pip
 - Numpy version: '1.15.1'
 - Quaternion version: '2018.7.5.21.55.13'

**Comment by scottdraves** [comment]
I get this too on Ubuntu 18, Python 3.6.6, numpy 1.14.5, quaternion v2018.7.5.21.55.13
the leading argument seems to trigger the bug.  replacing the quat array with a double array still leaks:
```
q = np.quaternion(0.1, 0.1, 0.1, 0.1)
da = np.float32([1.0]*100000000)
x = q * da
```

**Comment by moble** [comment]
Thanks for the detailed report.

I'm kind of at a loss as to how this is happening.  By inserting some printf statements, I've verified that the core function is being called [here](https://github.com/moble/quaternion/blob/97482b4e4a174789dd91808ad65255498980f222/numpy_quaternion.c#L235).  The function that's in is essentially the same as [this example](https://www.scipy-lectures.org/advanced/interfacing_with_c/interfacing_with_c.html#numpy-support), and the only dodgy thing I see in my code is the `Py_INCREF` a few lines down.  But the example shows a similar incref, and if I just remove it, I get segfaults, so I think it's correct.  I don't see anywhere else that I'm allocating anything that doesn't get "freed" — or certainly nothing that should have such significant size in memory.

I'll keep looking, but any help is much appreciated.  I still can't claim to really understand how numpy works...

**Comment by ctrlbrett** [comment]
Just to make sure this is not how numpy acts normally (without the quaternion library), I tested it out by changing doit() to

```python

def doit():
    q = np.array([0.1])
    qa = np.array([1.0] * 10000000)
    x = q  * qa

```

and I do NOT see the big blocks of memory sitting around. I am fairly sure it must have something to do with the quaternion library.

**Comment by moble** [comment]
Yeah, it's definitely in this code, but I just can't see where it's coming from.  I've just spent all morning trying to get valgrind working, but I'm on macos 10.13 which apparently is a no-go.  I'm trying a full debug build now to see if that gives me any more clues.

In addition to the adjustments noted above, if I simply adjust the corresponding line in the original code as
```python
q = np.array(np.quaternion(0.1, 0.1, 0.1, 0.1))
```
the leak also goes away.  But I have confirmed that this doesn't use [the function I pointed to above](https://github.com/moble/quaternion/blob/97482b4e4a174789dd91808ad65255498980f222/numpy_quaternion.c#L235).

**Comment by ctrlbrett** [comment]
Thanks, that work around actually may help us a lot in the mean time.

**Comment by moble** [comment]
Just a little more detail about [that suspicious INCREF](https://github.com/moble/quaternion/blob/97482b4e4a174789dd91808ad65255498980f222/numpy_quaternion.c#L254):

Using printf statements, I've verified that the reference count of `out_array` goes as follows:
  1. `PyArray_NewLikeArray` initializes it to 1 reference
  2. `NpyIter_New((PyArrayObject *)out_array, ...` adds 1, leaving it at 2
  3. `NpyIter_Deallocate(out_iter)` subtracts 1, leaving it at 1
  4. `Py_INCREF(out_array)` adds 1, leaving it at 2

So immediately before the return statement, `out_array` has a refcount of 2, which seems like 1 too many to me.  Now, if I remove that INCREF statement, the code will run and I can verify that it eliminates the leak.  However, if I also loop over `doit()` hundreds of times, I get eventually get a segfault without that INCREF.

On a related note, I've checked that [example that I pointed to](https://www.scipy-lectures.org/advanced/interfacing_with_c/interfacing_with_c.html#numpy-support), and have found that it also has a memory leak.  However, if I remove the INCREF in that code, it eliminates the leak but I *don't* get segfaults!

**Comment by moble** [comment]
I wonder if this is related to numpy/numpy#8503.  There, the issue is a memory leak when creating arrays of type `object`.  While the `quaternion` code is creating arrays of a specific type, it's not one of the built-in types, and the results do look similar...

**Comment by scottdraves** [comment]
Awesome thank you.
