### ISSUE TITLE
Python 3.7 compatibility

### ISSUE THREAD

**Issue by chernals** [moble/quaternion#93]
It appears that there is no Python 3.7 compatible version on conda-forge at this point.

Are there any actual incompatibilities or is it just a matter of testing and tagging?

So far I have been using it with python 3.7 (framework build on Mac) and pip.

**Comment by moble** [comment]
I don't see any reason it wouldn't work.  The problem has been that conda itself didn't support 3.7 until just a few weeks ago, which means that other packages have been slow to update, but I don't see why it won't work right now.  I'm taking the opportunity to bump some other versioning issues, so I hope to get around to making sure conda-forge gets the news by tomorrow, which means that it'll hopefully filter out in the next couple days.

**Comment by moble** [comment]
I've had to drop deployment for numpy 1.13 (though it's still compatible for anyone who wants to compile themselves), but conda-forge now includes versions for python 3.7.
