### ISSUE TITLE
Documentation / Api reference

### ISSUE THREAD

**Issue by Tezirg-Wrld3D** [moble/quaternion#95]
Is there a quick API reference / a web page where we can consult the list of prototypes exposed ? 

If not, thats probably low effort and helps people getting started.  Even a doxygen generated would do the trick.A t the moment I'm reading the code to figure out how to use the module.

**Comment by moble** [comment]
Other than a few examples on the README, there is not currently any such documentation.  Generally, I prefer to use the tab-completion and live help features of ipython for discovering how a module works — especially a relatively simple one like this.  As a result, I write to enable that approach.  But I would certainly have no problem including such a page on [the wiki](https://github.com/moble/quaternion/wiki), for example.  As you say, it would probably require little effort, so feel free!
