### ISSUE TITLE
Ship C interface

### ISSUE THREAD

**Issue by Kelvinrr** [moble/quaternion#98]
Quaternion.c/.h seem like they would make a great lightweight quaternion C library. If we could use the C-API directly for C/C++ projects would be beneficial. I imagine simply updating the feedstock would do (edit: just now realized this issue might be better on the feedstock 😅).

**Comment by moble** [comment]
I guess I'm not really sure how this could be done, or how it would be used.  Are you suggesting that `quaternion.h` should be installed into `~/anaconda/include` and some `quaternion.so` should installed into `~/anaconda/lib`?  And then would C/C++ projects be able to find those files through conda?  Is there some standard way of doing this?  And could it be turned off if it fouls up pip installations?
