### ISSUE TITLE
Install via pip requirements.txt error

### ISSUE THREAD

**Issue by rowanxyt** [moble/quaternion#99]
I was trying to do a pip install using a requirements.txt file and it failed. Details:
1) The pip command used: python -m pip install -r requirements.txt. Python==3.6.5, pip==9.0.3;
2) The requirements.txt contained two lines: line 1: numpy==1.15.0, line 2: numpy-quaternion==2018.11.3.1.0.41.

The error was: 

Collecting numpy-quaternion==2018.11.3.1.0.41 (from -r requirements.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/3c/5d/e58d67cd579061aa2c392dfeef510ba35b89d208d8ec689b0b0438c3632c/numpy-quaternion-2018.11.3.1.0.41.tar.gz
    Complete output from command python setup.py egg_info:
    The variable 'package_version' was not present in the environment
    Setup.py using strftime version='2018.12.12.21.45.36'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0iuc7nb6/numpy-quaternion/setup.py", line 54, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0iuc7nb6/numpy-quaternion/

**Environment**
 - Ubuntu 16.04

I know I could install them one at a time (numpy first and numpy-quaternion second) and it worked. But it would be more convenient if I could use the requirements.txt method.

**Comment by moble** [comment]
It looks like this may be doable with the hack from [this SO answer](https://stackoverflow.com/a/21621689/1194883) (despite the fact that Travis Oliphant himself said it was impossible in the answer just below that one, even though all the same techniques were available when he answered).  I'll give it a try next time I have a few minutes.

CC: @Achllle @jvgomez

**Comment by Achllle** [comment]
I tried this and it worked as long as you remove the default version of numpy that's installed on Travis using `sudo pip uninstall numpy -y`.

**Comment by bluenote10** [comment]
Would be great if this could be fixed because it breaks working with a single `pip install -r requirements.txt`.

There a lots of packages that depend on numpy w/ headers (pandas, sklearn, etc.), yet they don't depend on it at install time. How have they solved the problem, are they all using this "hack"?

**Comment by j9ac9k** [comment]
Here is the commit that addressed this w/ PyMC3

https://github.com/pymc-devs/pymc/pull/94/files

**Comment by moble** [comment]
My most recent commits have tried to implement the various proposed solutions.  I'm hesitant to close this issue, though, because I've never actually run into the problem.  So would the rest of you please try it out?

**Comment by Achllle** [comment]
I reverted the hacks that we discussed here and ran it on travis, you can see that the build succeeded [here](https://travis-ci.com/Achllle/dual_quaternions_ros/builds/117012631). However it seems like I still need to remove the root numpy installation and reinstall it in the `.travis.yml` for it to work ([failing build](https://travis-ci.com/Achllle/dual_quaternions_ros/builds/117013227)).
However I did recently try installing on a new fresh installation of Ubuntu 16.04 and it did fail (don't remember the exact error, but it was also a numpy issue).

**Comment by moble** [comment]
> However I did recently try installing on a new fresh installation of Ubuntu 16.04 and it did fail (don't remember the exact error, but it was also a numpy issue).

This is just within the past day.

In fact, just now I've added some more things that people have claimed make pip work correctly.  At this point, I'm past the end of my rope with pip.  If this isn't working now for some other pip configurations, it's never going to work.  But I really think it should work, so I'm closing this issue.

**Comment by rowanxyt** [comment]
Yeah I tried the "python -m pip install -r requirements.txt" method with the requirements.txt containing numpy==1.15.0 and numpy-quaternion==2019.6.26.15.8.24 and it worked. Thank you!
